version: 0.2

phases:

  build:
    commands:
      - echo "Criando o arquivo .env..."
      - |
        cat <<EOF > .env
        # Variáveis de ambiente da aplicação Next.js
        NODE_ENV=production
        NEXT_PUBLIC_API_URL=$API_URL
        EOF
      - echo "Arquivo .env criado com sucesso!"
      - echo "Listando arquivos do diretório:"
      - ls -la

artifacts: 
  type: zip
  files:
    - '**/*' 
  