version: 0.2

phases:
  build:
    commands:
      - echo "Gerando .env para build local"
      - |
        cat <<EOF > .env
        NODE_ENV=production
        NEXT_PUBLIC_API_URL=$API_URL
        EOF
      - echo ".env criado"

artifacts:
  files:
    - '**/*'
    - '!.git/**'
    - '!node_modules/**'
    - '!.next/cache/**'
